name: gan
dependencies:
  - tensorflow-gpu
  - pandas
  - matplotlib
  - keras
  - opencv
  - numpy
  - Pillow
# TODO1 do it automatically
# pip:
#  - flickrapi
#  - IPython
#  - opencv-python
#  - tensorflow-addons
#  - split-folders